title: Mohammed Al-Barbari 
description: The personal blog of Mohammed Al-Barbari
url: https://m4dm0e.github.io
author: Mohammed Al-Barbari
avatar: /logo.png
email: moe@grodriket.com
location: AlJawf, Yemen

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

google_analytics: UA-163113883-1


# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: m4dm0e-github-io

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "Mohammed Al-Barbari"
      image: "logo.png"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "Mohammed Al-Barbari"
      image: "logo.png"


twitter:
  username: m4dm0e
  card: summary
logo: logo.png
social:
  name: Mohammed Al-Barbari
  links:
    - https://twitter.com/m4dm0e
    - https://www.facebook.com/F3rzYe
    - https://github.com/M4DM0E

# google_site_verification: 
lang: en
